### ISSUE TITLE
How did you generate groundtruth for CASIA2?

### ISSUE THREAD

**Issue by gyheart** [namtpham/casia2groundtruth#2] opened 2019-07-30 06:58 UTC
I want to generate groundtruth for CASIA1. Can you tell me how did you generate groundtruth for CASIA2? Thanks.

**Comment by namtpham** [comment] 2019-09-09 08:38
Duplicate of #

**Comment by namtpham** [comment] 2019-09-09 08:39
Duplicate of #1

**Closed as completed by namtpham** 2019-09-09 08:39 UTC
